### ISSUE TITLE
I'm very interested in your research. How to avoid the internal collision of agents and how to avoid obstacles perfectly?

### ISSUE THREAD

**Issue by dlml** [atlin23/apac-net#1]

**Comment by dlml** [comment]
Only using HJB can avoid the internal collision avoidance of agent, but mfg has no concept of individual.

**Comment by atlin23** [comment]
Hey sorry for the delay in reply! Yeah with APAC-Net the generator produces samples from a probability distributions, so it's not completely guaranteed that we will avoid collisions or avoid obstacles. 

But I suspect if you make the collision penalty or obstacle penalty high enough, you can avoid collisions.

For obstacles, I suppose one strategy is to make the virtual obstacle bigger than the actual obstacle so there is "enough room to breath" when going around obstacles.

Hope that helps, and thank you for your interest!

**Comment by atlin23** [comment]
I'll close the issue for now, but please feel free to open it if you have more questions.

**Comment by dlml** [comment]
Thank you for your reply. Now I have another question about density bifurcation, such as breaking through a circular obstacle (Gaussian repulsion), how to let the agent walk from both sides instead of one side.

**Comment by atlin23** [comment]
Yeah density is bifurcation is possible. We have an experiment in the appendix of the paper where the agents go around an elliptical object and the density splits.

**Comment by dlml** [comment]
In the dynamic equation of four rotor UAV, I don't quite understand why the density rho is placed in that position. Do you have any references? 

<img width="800" alt="图片" src="https://user-images.githubusercontent.com/35597616/129464461-c7496f02-7f21-4823-97c4-1d796720743d.png">

**Comment by dlml** [comment]
And I found that the calculation of Hamiltonian quantity does not include rho

**Comment by atlin23** [comment]
Hey sorry for the delay in response, but that is admittedly a typo. We'll work on getting the typo fixed soon.

Edit: to clarify, please just pretend the rho isn't there and everything is correct.

Thank you!

**Comment by dlml** [comment]
Another problem is that the Hamiltonian I calculated is different from your paper. It may be that the overall difference is a minus sign. Can you share wechat? I'm doing multi group research now.

**Comment by atlin23** [comment]
Yeah sure. I don't think github has a private messaging feature so perhaps you can email me your wechat? My email can be found here: www.math.ucla.edu/~atlin

You may also be interested in our implementation of the quadcopter (in the envs folder, quadcopter.py).
